export let tableBody=[
    
        {
          id:1,
          img: "/images/neil-sims.png",
          name: "ali",
          lastName: "asdf",
          email: "asdf@gmail.com",
          phoneNumber: "asdf",
          department: "fasd",
          company: "adsf",
          currentPassword: "asdf",
          newPassword: "asdf",
          position: "front-end developer",
          country: "United States",
          status: "active",
          price: 2,
        },
        {
          id:2,
          img: "/images/neil-sims.png",
          name: "hüseyin",
          lastName: "asdf",
          email: "asdf@gmail.com",
          phoneNumber: "asdf",
          department: "fasd",
          company: "adsf",
          currentPassword: "asdf",
          newPassword: "asdf",
          position: "ufront-end developer",
          country: "ğUnited States",
          status: "kactive",
          price: 35,
        },
        {id:8,
          img: "/images/neil-sims.png",
          name: "ahmet",
          lastName: "asdf",
          email: "asdf@gmail.com",
          phoneNumber: "asdf",
          department: "fasd",
          company: "adsf",
          currentPassword: "asdf",
          newPassword: "asdf",
          position: "tfront-end developer",
          country: "yUnited States",
          status: "jactive",
          price: 15,
        },
        {id:7,
          img: "/images/neil-sims.png",
          name: "recep",
          lastName: "asdf",
          email: "asdf@gmail.com",
          phoneNumber: "asdf",
          department: "fasd",
          company: "adsf",
          currentPassword: "asdf",
          newPassword: "asdf",
          position: "afront-end developer",
          country: "xUnited States",
          status: "gactive",
          price: 1,
        },
        {id:6,
          img: "/images/neil-sims.png",
          name: "hasan",
          lastName: "asdf",
          email: "asdf@gmail.com",
          phoneNumber: "asdf",
          department: "fasd",
          company: "adsf",
          currentPassword: "asdf",
          newPassword: "asdf",
          position: "front-end developer",
          country: "United States",
          status: "active",
          price: 2,
        },
        {
          id:3,
          img: "/images/neil-sims.png",
          name: "arif",
          lastName: "asdf",
          email: "asdf@gmail.com",
          phoneNumber: "asdf",
          department: "fasd",
          company: "adsf",
          currentPassword: "asdf",
          newPassword: "asdf",
          position: "ufront-end developer",
          country: "ğUnited States",
          status: "kactive",
          price: 35,
        },
        {
          id:4,
          img: "/images/neil-sims.png",
          name: "kemal",
          lastName: "asdf",
          email: "asdf@gmail.com",
          phoneNumber: "asdf",
          department: "fasd",
          company: "adsf",
          currentPassword: "asdf",
          newPassword: "asdf",
          position: "tfront-end developer",
          country: "yUnited States",
          status: "jactive",
          price: 15,
        },
        {
          id:5,
          img: "/images/neil-sims.png",
          name: "murat",
          lastName: "asdf",
          email: "asdf@gmail.com",
          phoneNumber: "asdf",
          department: "fasd",
          company: "adsf",
          currentPassword: "asdf",
          newPassword: "asdf",
          position: "afront-end developer",
          country: "xUnited States",
          status: "gactive",
          price: 1,
        },
      
        {
          id:9,
          img: "/images/neil-sims.png",
          name: "hüseyin",
          lastName: "asdf",
          email: "asdf@gmail.com",
          phoneNumber: "asdf",
          department: "fasd",
          company: "adsf",
          currentPassword: "asdf",
          newPassword: "asdf",
          position: "front-end developer",
          country: "United States",
          status: "active",
          price: 2,
        },
        {
          id:10,
          img: "/images/neil-sims.png",
          name: "jack",
          lastName: "asdf",
          email: "asdf@gmail.com",
          phoneNumber: "asdf",
          department: "fasd",
          company: "adsf",
          currentPassword: "asdf",
          newPassword: "asdf",
          position: "ufront-end developer",
          country: "ğUnited States",
          status: "kactive",
          price: 35,
        },
        {id:11,
          img: "/images/neil-sims.png",
          name: "jason",
          lastName: "asdf",
          email: "asdf@gmail.com",
          phoneNumber: "asdf",
          department: "fasd",
          company: "adsf",
          currentPassword: "asdf",
          newPassword: "asdf",
          position: "tfront-end developer",
          country: "yUnited States",
          status: "jactive",
          price: 15,
        },
        {id:12,
          img: "/images/neil-sims.png",
          name: "hans",
          lastName: "asdf",
          email: "asdf@gmail.com",
          phoneNumber: "asdf",
          department: "fasd",
          company: "adsf",
          currentPassword: "asdf",
          newPassword: "asdf",
          position: "afront-end developer",
          country: "xUnited States",
          status: "gactive",
          price: 1,
        },
        {id:13,
          img: "/images/neil-sims.png",
          name: "totti",
          lastName: "asdf",
          email: "asdf@gmail.com",
          phoneNumber: "asdf",
          department: "fasd",
          company: "adsf",
          currentPassword: "asdf",
          newPassword: "asdf",
          position: "front-end developer",
          country: "United States",
          status: "active",
          price: 2,
        },
        {
          id:14,
          img: "/images/neil-sims.png",
          name: "zidane",
          lastName: "asdf",
          email: "asdf@gmail.com",
          phoneNumber: "asdf",
          department: "fasd",
          company: "adsf",
          currentPassword: "asdf",
          newPassword: "asdf",
          position: "ufront-end developer",
          country: "ğUnited States",
          status: "kactive",
          price: 35,
        },
        {
          id:15,
          img: "/images/neil-sims.png",
          name: "raul",
          lastName: "asdf",
          email: "asdf@gmail.com",
          phoneNumber: "asdf",
          department: "fasd",
          company: "adsf",
          currentPassword: "asdf",
          newPassword: "asdf",
          position: "tfront-end developer",
          country: "yUnited States",
          status: "jactive",
          price: 15,
        },
        {
          id:16,
          img: "/images/neil-sims.png",
          name: "cafu",
          lastName: "asdf",
          email: "asdf@gmail.com",
          phoneNumber: "asdf",
          department: "fasd",
          company: "adsf",
          currentPassword: "asdf",
          newPassword: "asdf",
          position: "afront-end developer",
          country: "xUnited States",
          status: "gactive",
          price: 1,
        },
      
]

const addIdToTableData = (tableData) => {
  return tableData.map((user, index) => ({
    id: index + 1,
    ...user,
  }));
};

export const tableBodyWithId = addIdToTableData(tableBody);